### ISSUE TITLE
Repository license

### ISSUE THREAD

**Issue by Aspie96** [fiatjaf/nostr-relay-registry#75]
Hi!

@fiatjaf and @Cameri, would you consider adding a license for this repository?

**Comment by fiatjaf** [comment]
Why? There is nothing in this repository worth of licensing. It's free, public domain, please copy it.

**Comment by Cameri** [comment]
> Hi!
> 
> 
> 
> @fiatjaf and @Cameri, would you consider adding a license for this repository?

Do whatever you want with it 💜

**Comment by Aspie96** [comment]
> Why? There is nothing in this repository worth of licensing. 

The script are all very simple, but I still asked to make sure.

> It's free, public domain, please copy it.

Great, thanks!

> Do whatever you want with it 💜

Thanks!
